### ISSUE TITLE
dataset downloading

### ISSUE THREAD

**Issue by WWWzq-01** [YukeWang96/MGG-OSDI23-AE#3]
Hi, I'm encountering a problem when downloading datasets.

command
```shell
wget https://storage.googleapis.com/mgg_data/local.tar.gz
```

output
```shell
--2024-03-09 22:04:49--  https://storage.googleapis.com/mgg_data/local.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.163.59, 142.251.43.27, 142.251.42.251
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.163.59|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-03-09 22:04:50 ERROR 404: Not Found.
```
Is the webpage no longer active, or is there another issue?

**Comment by YukeWang96** [comment]
Hi, we are currently migrating out our project data from previous Google Cloud storage. We will later follow up with the updated location. Thanks!

**Comment by YukeWang96** [comment]
> Hi, I'm encountering a problem when downloading datasets.
> 
> command
> 
> ```shell
> wget https://storage.googleapis.com/mgg_data/local.tar.gz
> ```
> 
> output
> 
> ```shell
> --2024-03-09 22:04:49--  https://storage.googleapis.com/mgg_data/local.tar.gz
> Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.163.59, 142.251.43.27, 142.251.42.251
> Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.163.59|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2024-03-09 22:04:50 ERROR 404: Not Found.
> ```
> 
> Is the webpage no longer active, or is there another issue?

Just finish the data migration, please run the updated commands for downloading the datasets.

**Comment by WWWzq-01** [comment]
thank you !!

**Comment by WWWzq-01** [comment]
sorry,I'm still encountering a problem with downloading the library.
The command `wget https://storage.googleapis.com/mgg_data/local.tar.gz` is used to download the library, but now that resource appears to be invalid.

**Comment by YukeWang96** [comment]
Just fix it with new command

**Comment by WWWzq-01** [comment]
Thanks！
