### ISSUE TITLE
A question about the section 1.4:Compile implementation.

### ISSUE THREAD

**Issue by WWWzq-01** [YukeWang96/MGG-OSDI23-AE#4]
The command sequence `mkdir build && cd build && cmake .. && cd ..` seems to be missing the make step. In my opinion, it should include make as follows: `mkdir build && cd build && cmake .. && make && cd ..`. Otherwise, the compilation artifacts will not be generated. For example, if I don't run the make command and then try to run python 2_MGG_NP.py directly, an error will be displayed.
<img width="563" alt="image" src="https://github.com/YukeWang96/MGG_OSDI23/assets/52373880/d7461b5a-f886-4f09-8a4d-2db6a473416d">

**Comment by YukeWang96** [comment]
May I know if you first launch the docker container before running these compilation commands?

**Comment by WWWzq-01** [comment]
Yes, I have launched the Docker container first.
