### ISSUE TITLE
Compilation Error During make Command Execution

### ISSUE THREAD

**Issue by WWWzq-01** [YukeWang96/MGG-OSDI23-AE#5]
After I run the command `mkdir build && cd build && cmake ..`,I subsequently run `make`. Then an error is shown as follows:

<img width="919" alt="image" src="https://github.com/YukeWang96/MGG_OSDI23/assets/52373880/6137f985-fb54-4505-b428-014ef4347071">

can you fix it ?

**Comment by YukeWang96** [comment]
please try this `./0_mgg_build.sh` instead of `make`

**Comment by WWWzq-01** [comment]
Thank you. Could you please tell me if MGG can be operated using only a single GPU?

**Comment by YukeWang96** [comment]
Thanks for your interest! MGG is tailored for multi-GPU with MPI and NVSHMEM, I would recommend to checkout our another project GNNAdvisor for single-GPU GNN computation. https://github.com/YukeWang96/GNNAdvisor_OSDI21

**Comment by WWWzq-01** [comment]
Thank you for the response and the recommendation! I will check out GNNAdvisor.
